#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.53
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color  "#c274a4"


~/.config/polybar/autostart.sh
